INSERT INTO TB_CATEGORY (NAME, CATEGORY_NUMBER) VALUES ('Computing', 984383);

INSERT INTO TB_PRODUCTS (NAME, DESCRIPTION, PRICE, PRODUCT_NUMBER) VALUES ('Notebook Lenovo', 'Ideapad S145', 3499.00, 984398);
INSERT INTO TB_PRODUCTS (NAME, DESCRIPTION, PRICE, PRODUCT_NUMBER) VALUES ('Notebok Dell', 'IdeadPad S234', 4000.00, 837443);
INSERT INTO TB_PRODUCTS (NAME, DESCRIPTION, PRICE, PRODUCT_NUMBER) VALUES ('Notebook Dell', 'IdeadPad S4354', 6500.00, 943094);
INSERT INTO TB_PRODUCTS (NAME, DESCRIPTION, PRICE, PRODUCT_NUMBER) VALUES ('Notebook Lenovo', 'IdeadPad S4309', 8000.00, 439054);
INSERT INTO TB_PRODUCTS (NAME, DESCRIPTION, PRICE, PRODUCT_NUMBER) VALUES ('MacBook Pró', 'Ultra I9', 18000.00, 328943);
INSERT INTO TB_PRODUCTS (NAME, DESCRIPTION, PRICE, PRODUCT_NUMBER) VALUES ('Notebook Dell', 'IdeaPad S9043', 13000.00, 945402);
INSERT INTO TB_PRODUCTS (NAME, DESCRIPTION, PRICE, PRODUCT_NUMBER) VALUES ('Notebook Dell', 'IdeadPad S3243', 9000.00, 839203);
INSERT INTO TB_PRODUCTS (NAME, DESCRIPTION, PRICE, PRODUCT_NUMBER) VALUES ('Notebook Samsung', 'Ideapad S9843', 12000.00, 984389);
INSERT INTO TB_PRODUCTS (NAME, DESCRIPTION, PRICE, PRODUCT_NUMBER) VALUES ('Notebook Lenovo', 'ThinkPad I5', 8000.00, 983292);
INSERT INTO TB_PRODUCTS (NAME, DESCRIPTION, PRICE, PRODUCT_NUMBER) VALUES ('Notebook Samsung', 'IdeadPad S5432', 10000.00, 984332);
INSERT INTO TB_PRODUCTS (NAME, DESCRIPTION, PRICE, PRODUCT_NUMBER) VALUES ('Notebook Samsung', 'IdeadPad S4398', 6000.00, 983203);
INSERT INTO TB_PRODUCTS (NAME, DESCRIPTION, PRICE, PRODUCT_NUMBER) VALUES ('Notebook Samsung', 'IdeadPad S5432', 5000.00, 983053);
INSERT INTO TB_PRODUCTS (NAME, DESCRIPTION, PRICE, PRODUCT_NUMBER) VALUES ('Notebook Samsung', 'IdeadPad S5442', 7000.00, 984393);
INSERT INTO TB_PRODUCTS (NAME, DESCRIPTION, PRICE, PRODUCT_NUMBER) VALUES ('Notebook Dell', 'ThinkPad I9', 9000.00, 872032);
INSERT INTO TB_PRODUCTS (NAME, DESCRIPTION, PRICE, PRODUCT_NUMBER) VALUES ('Notebook Dell', 'IdeaPad I7', 8000.00, 984302);
INSERT INTO TB_PRODUCTS (NAME, DESCRIPTION, PRICE, PRODUCT_NUMBER) VALUES ('Notebook Lenovo', 'ThinkPad I3', 4000.00, 984322);
INSERT INTO TB_PRODUCTS (NAME, DESCRIPTION, PRICE, PRODUCT_NUMBER) VALUES ('Notebook Lenovo', 'ThinkPad I5', 9000.00, 984395);
INSERT INTO TB_PRODUCTS (NAME, DESCRIPTION, PRICE, PRODUCT_NUMBER) VALUES ('Macbook Pró', 'Air Ultra I9', 19000.00, 984398);
INSERT INTO TB_PRODUCTS (NAME, DESCRIPTION, PRICE, PRODUCT_NUMBER) VALUES ('Macbook Pró', 'Air I7', 16000.00, 843973);
INSERT INTO TB_PRODUCTS (NAME, DESCRIPTION, PRICE, PRODUCT_NUMBER) VALUES ('Notebook Lenovo', 'ThinkPad I7', 12000.00, 983298);

INSERT INTO TB_CATEGORY_PRODUCTS (CATEGORY_ID, PRODUCT_ID) VALUES (1, 1);
INSERT INTO TB_CATEGORY_PRODUCTS (CATEGORY_ID, PRODUCT_ID) VALUES (1, 2);
INSERT INTO TB_CATEGORY_PRODUCTS (CATEGORY_ID, PRODUCT_ID) VALUES (1, 3);
INSERT INTO TB_CATEGORY_PRODUCTS (CATEGORY_ID, PRODUCT_ID) VALUES (1, 4);
INSERT INTO TB_CATEGORY_PRODUCTS (CATEGORY_ID, PRODUCT_ID) VALUES (1, 5);
INSERT INTO TB_CATEGORY_PRODUCTS (CATEGORY_ID, PRODUCT_ID) VALUES (1, 6);
INSERT INTO TB_CATEGORY_PRODUCTS (CATEGORY_ID, PRODUCT_ID) VALUES (1, 7);
INSERT INTO TB_CATEGORY_PRODUCTS (CATEGORY_ID, PRODUCT_ID) VALUES (1, 8);
INSERT INTO TB_CATEGORY_PRODUCTS (CATEGORY_ID, PRODUCT_ID) VALUES (1, 9);
INSERT INTO TB_CATEGORY_PRODUCTS (CATEGORY_ID, PRODUCT_ID) VALUES (1, 10);
INSERT INTO TB_CATEGORY_PRODUCTS (CATEGORY_ID, PRODUCT_ID) VALUES (1, 11);
INSERT INTO TB_CATEGORY_PRODUCTS (CATEGORY_ID, PRODUCT_ID) VALUES (1, 12);
INSERT INTO TB_CATEGORY_PRODUCTS (CATEGORY_ID, PRODUCT_ID) VALUES (1, 13);
INSERT INTO TB_CATEGORY_PRODUCTS (CATEGORY_ID, PRODUCT_ID) VALUES (1, 14);
INSERT INTO TB_CATEGORY_PRODUCTS (CATEGORY_ID, PRODUCT_ID) VALUES (1, 15);
INSERT INTO TB_CATEGORY_PRODUCTS (CATEGORY_ID, PRODUCT_ID) VALUES (1, 16);
INSERT INTO TB_CATEGORY_PRODUCTS (CATEGORY_ID, PRODUCT_ID) VALUES (1, 17);
INSERT INTO TB_CATEGORY_PRODUCTS (CATEGORY_ID, PRODUCT_ID) VALUES (1, 18);
INSERT INTO TB_CATEGORY_PRODUCTS (CATEGORY_ID, PRODUCT_ID) VALUES (1, 19);
INSERT INTO TB_CATEGORY_PRODUCTS (CATEGORY_ID, PRODUCT_ID) VALUES (1, 20);


